
export JL_debian=false
export JL_fresh=n
export JLIVEisopathF=$JLdir/JLIVEisopath
export JLIVEdirF=$JLdir/JLIVEdir
export JL_configfile="$JLdir/.config"
export JL_sconf="config.conf"
export JL_sconf_file_d="$JLdir/$JL_sconf"
export JL_terminal1=x-terminal-emulator
export JL_terminal2=xterm
export JL_lockF=/tmp/JL_lock
export JL_timeoutd=10
export JL_casper=casper
export JL_logdirtmp="/tmp/.neurobin/JLIVECD"
export JL_ynF="$JL_logdirtmp/yn"
export JL_resolvconf=run/resolvconf/resolv.conf #must not start with /
export JL_rhpn=RETAINHOME
export JL_dnpn=DISKNAME
export JL_xhpn=XHOST
export JL_fcpn=FASTCOMPRESSION
export JL_ufpn=UEFI
export JL_hbpn=HYBRID
export JL_tmn=TIMEOUT
export JL_t1n=TERMINAL1
export JL_t2n=TERMINAL2
