#!/bin/bash
JLIVEdirF=/usr/local/JLIVECD/JLIVEdir
if [ -f "$JLIVEdirF" ]; then
  livedir="$(cat "$JLIVEdirF")"
else
  echo "May be this is a new project, run JLstart instead"
  exit 1
fi
cd "$livedir"
echo "Preparing network connection for chroot in $livedir..."
cp /etc/hosts edit/etc/
rm edit/etc/resolv.conf
cp -L /etc/resolv.conf edit/etc/resolv.conf
echo "Network connection shlould be available in chroot now....."
