#!/bin/bash
cd "$(dirname "$BASH_SOURCE")"

export JLdir=/usr/local/JLIVECD
cd $JLdir
. ./defconf.sh
. ./funcs.sh
mkdir -p "$JL_logdirtmp"


trap finish EXIT
trap finish SIGTERM

help="
******** JLstart ********
Usage:
    -ub       ubuntu mode
    -db       debian mode
    -h        help menu
    -v        version info
See JLopt -h for settings.
"

live_os=
while [[ $# > 0 ]]
do
    case "$1" in
    	-ub|--ubuntu)
    		live_os=ubuntu
    		;;
        -db|--debian)
        	live_os=debian
            ;;
        -v|--version)
        	JLopt --version
        	exit 0
            ;;
        -h|--help)
            echo "$help"
            exit 0
            ;;
        *)
            echo "$help"
            echo "invalid option: '$1'"
            exit 1
        	;;
    esac
    shift
done

echo "***********************************************"
echo "*** Don't use quotation in file/folder path ***"
echo "***********************************************"

chknorm

#if live_os is not given, then force to select one:
if [ "$live_os" = "" ]; then
    echo
    echo "***************** MODE SELECT *****************"
    echo "* For Ubuntu family & Linux Mint: ubuntu mode *"
    echo "* For Debian:                     debian mode *"
    echo "***********************************************"
	live_os=$(mode_select)
fi

if [ "$live_os" = debian ]; then
    JL_debian=true;
    JL_casper=live
    JL_resolvconf=var/run/NetworkManager/resolv.conf #must not start with /
fi


JL_fresh=$(get_yn "Is this a new project: (y/n)?: ")

echo $JL_fresh > "$JL_ynF"

if [ "$JL_fresh" = y -o "$JL_fresh" = Y ]; then
  fresh_start
fi

if $JL_debian; then
    sudo  ./main/custom_desktop -db
else
    sudo  ./main/custom_desktop
fi
