#!/bin/bash
export JLdir=/usr/local/JLIVECD
cd $JLdir
set -a
. ./defconf.sh
. ./funcs.sh
. "$JL_configfile"
set +a
chkroot
mkdir -p "$JL_logdirtmp"

help="
******** JLstart ********
Usage:
    -ub       ubuntu mode
    -db       debian mode
    -al       archlinux mode
    -h        help menu
    -v        version info
See JLopt -h for settings.
"

export live_os=
while [[ $# > 0 ]]
do
    case "$1" in
    	-ub|--ubuntu)
    		live_os=ubuntu
    		;;
        -db|--debian)
        	live_os=debian
            ;;
        -al|--archlinux)
            live_os=archlinux
            ;;
        -v|--version)
        	JLopt --version
        	exit 0
            ;;
        -h|--help)
            echo "$help"
            exit 0
            ;;
        *)
            echo "$help"
            echo "invalid option: '$1'"
            exit 1
        	;;
    esac
    shift
done

JL_fresh=$(get_yn "Is this a new project: (y/n)?: ")
if [ "$JL_fresh" = y -o "$JL_fresh" = Y ]; then
  fresh_start
fi

#trap_with_arg finish SIGTERM EXIT SIGQUIT

yn="$JL_fresh"

if [ "$yn" = y -o "$yn" = Y ]; then
	JL_fresh=y
else
	JL_fresh=n
fi

echo
echo "***********************************************"
echo "*** Default value for (Y/n) prompts is 'n'  ***"
echo "*** unless specified otherwise.             ***"
echo "*** If you just hit enter without giving    ***"
echo "*** anything to a prompt, it will take the  ***"
echo "*** default (previous) value.               ***"
echo "***********************************************"

jlcd_start ${1+"$@"}
