#!/bin/bash
# ##############################################################################
# ############################### JLIVECD ######################################
# ##############################################################################
#            Copyright (c) 2015-2017 Md. Jahidul Hamid
# 
# -----------------------------------------------------------------------------
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
# 
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
# 
#     * The names of its contributors may not be used to endorse or promote 
#       products derived from this software without specific prior written
#       permission.
#       
# Disclaimer:
# 
#     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#     AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#     IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#     ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
#     LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#     CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#     SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#     INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#     CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#     ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#     POSSIBILITY OF SUCH DAMAGE.
# ##############################################################################

JL_debian=false
JL_ubuntu=false
JL_archlinux=false
JL_newrun=false
while [ $# -gt 0 ]; do
    case "$1" in
        -db|--debian)
            JL_debian=true
            ;;
        -ub|--ubuntu)
            JL_ubuntu=true
            ;;
        -al|--archlinux)
            JL_archlinux=true
            ;;
        -n|--new)
            JL_newrun=true
            ;;
    esac
    shift
done

echo '*** Preparing chroot...'
export HOME=/root
export LC_ALL=C
#dbus-uuidgen > /var/lib/dbus/machine-id #ubuntu 9.10 only
#dpkg-divert --local --rename --add /sbin/initctl 2>/dev/null #ubuntu 9.10 only
#ln -s /bin/true /sbin/initctl #ubuntu 9.10 only
ln -sf /"$JL_resolvconf" /etc/ 2>/dev/null
mv -f /hosts /etc/hosts
mv -f /resolv.conf /etc/resolv.conf
if $JL_newrun; then
    pacman-key --init 2>/dev/null
    pacman-key --populate archlinux 2>/dev/null
fi
echo '*** Chroot preparation finished'
echo "
*****************************************
*** This is the chroot terminal       ***
*** Run './help' to get help for      ***
*** debian/ubuntu based distro        ***
*** and './help -al' to get archlinux ***
*** specific help.                    ***
*****************************************
"
