#!/bin/bash
export JLdir=/usr/local/JLIVECD
cd $JLdir
set -a
. ./defconf.sh
. ./funcs.sh
. "$JL_configfile" #must be after defconf
set +a

chkroot

if [ "$1" = -db ]; then
	JL_debian=true;
	JL_casper=live
	JL_resolvconf=var/run/NetworkManager/resolv.conf #must not start with /
fi


#trap_with_arg finish SIGTERM EXIT SIGQUIT

yn="$(cat "$JL_ynF")"

if [ "$yn" = y -o "$yn" = Y ]; then
	JL_fresh=y
else
	JL_fresh=n
fi

echo
echo "***********************************************"
echo "*** default value for (Y/n) prompts is 'n'  ***"
echo "*** If you just hit enter without giving    ***"
echo "*** anything to a prompt, it will take your ***"
echo "*** previous input (if any).                ***"
echo "***********************************************"

jlcd_start ${1+"$@"}
