#!/bin/bash
cd $(dirname $0)
if [ "$(id -u)" == "0" ]; then
echo -e "......Sorry.....you need to run this as a normal user, not root....."
exit 1
fi
maindir=$PWD
c=1
d=1
while [ $c == 1 ]
do
c=2
read -e -p "......Where do you want to save your project ?.....choose a directory where you have full permission)..Enter path: " livedir
livedir=${livedir/\~/$HOME}
[ -d $livedir ] && echo "***$livedir Exists, Contents will be overwritten***" || mkdir $livedir
if [ ! -d "$livedir" ]; then
c=1
echo ".....Invalid directory name/path!"
fi
done
cd "$livedir"
[ -d mnt ] && echo "***$livedir/mnt Exists, Contents will be overwritten***" || mkdir mnt
while [ $d == 1 ]
do
d=2
read -e -p "......Enter the path to your base iso image (without .iso): " isopath
isopath=${isopath/\~/$HOME}
if [ ! -f "${isopath[@]}.iso" ]; then
d=1
echo "......Couldn't find the iso"
else
echo "......Found iso: ${isopath[@]}.iso"
echo "${isopath[@]}" > $HOME/JLIVEisopath
fi
done
[ -d extracted ] && echo "***$livedir/extracted Exists, Contents will be overwritten***" || mkdir extracted
rm -f "$HOME/JLIVEdir"
rm -f "$HOME/JLIVEyn"
echo "$livedir" > "$HOME/JLIVEdir"
echo y > $HOME/JLIVEyn
