#!/bin/bash

echo '*** Preparing chroot...'
export HOME=/root
export LC_ALL=C
dbus-uuidgen > /var/lib/dbus/machine-id
dpkg-divert --local --rename --add /sbin/initctl
ln -s /bin/true /sbin/initctl
#ln -sf /"$JL_resolvconf" /etc/
echo '*** Chroot preparation finished'
echo "
***********************************
*** This is the chroot terminal ***
*** Run './help' to get help    ***
***********************************
"
